新增日本新字體。
BYVoid/OpenCC pull request #371
Opened 2020-02-21 07:49 UTC by edward-martyr

包括唯一標準的日本字形（如「粤」而不是「_粵_」，「隣」而不是「_鄰_」。「_粵_」、「_鄰_」在《大辞林》皆查無此字）以及擴張新字體（如被新聞界使用的「𦜝」，標準字形是「_臍_」）。

2020-02-21 08:32 UTC, sgalal requested changes
<div lang="zh-HK">

謝謝！

粗略地看了一下，發現有下面兩個問題，你能否再重新校對一次？

一、異體字的情況

例如：

```raw
貮	貳
```

OpenCC 標準字就是「貳」，不是「貮」，因此不應該收錄。

又如：

```raw
龝	穐
```

左邊「龝」是異體字，不是 OpenCC 標準字，因此不應該收錄。

二、不恰當的地方

例如：

```raw
卒	卆
```

日文寫「卒業」，不是「卆業」吧？

又如：

```raw
蕟	𫈴
```

右邊這個「𫈴」下面是「癶」＋「开」，不是「発」。左右兩字不是同一個字。

</div>

2020-02-23 03:20 UTC, edward-martyr commented
@sgalal 你好，

我檢查了一下相關問題，

**異體字**
`貮	貳` 應該予以刪除。
`龝	穐` 是因爲「龝」是「秋」的異體字嗎？如果是這個原因，應刪除。

**「卒」及其孳乳字**
日本新字體對該字的處理比較奇怪：孳乳字（如「碎」「醉」）一併簡化（如「砕」「酔」）。雖然「卒」作「卆」例亦有，不過確實以「卒」爲通行用法（68%，見[「卆」と「卒」](https://dictionary.sanseido-publ.co.jp/column/%E7%AC%AC17%E5%9B%9E%E3%80%8C%E5%8D%86%E3%80%8D%E3%81%A8%E3%80%8C%E5%8D%92%E3%80%8D)），故考慮刪除，而其他孳乳字如 `埣	𡉻` 予以保留。

**「𫈴」字形**
IPA明朝中「𫈴」（CJK UNIFIED IDEOGRAPH-2B234）的字形是
<img width="130" alt="𫈴" src="https://user-images.githubusercontent.com/42882301/75102764-b0527d80-562b-11ea-8a1e-d29ab2ace512.png">
GlyphWiki 卻錄有 `⿱艹発` 及 `⿳艹癶开` [兩種寫法](http://glyphwiki.org/wiki/Special:Search?search=%F0%AB%88%B4&buttons=%E6%A4%9C%E7%B4%A2)，也並無分別 Unicode 碼位（`⿱艹発` 作 `u2b234-ue0100`）。我傾向認爲 `⿱癶开` 是 `発` 在某些字體使用錯誤的字形構成描述而做出的誤形/錯誤實現，並不影響 `u2b234` 這個碼位代表「蕟」的擴張新字體，因而不應刪除。

2020-02-24 10:21 UTC, sgalal commented
<div lang="zh-HK">

關於「𫈴」字我補充一下，該字位於擴展 C 區，經查詢 Unicode 相關文檔可知該字是台灣提交的，來源為 CNS 11643 中文標準交換碼。在 CNS 11643 中文全字庫搜索可知，該字讀音為 <span lang="cmn-Bopo">ㄗㄤˋ</span>/<span lang="cmn-Latn">zàng</span>，來源為內政部户政用字。因此該字與「蕟」是不一樣的。

- 擴展 C 區：<https://www.unicode.org/charts/PDF/U2A700.pdf>
- CNS 11643 中文全字庫搜索：<https://www.cns11643.gov.tw/wordView.jsp?ID=869492>

</div>

2020-02-25 04:48 UTC, edward-martyr commented
@sgalal 
原來如此！謝謝，我已修改。

2020-03-27 15:42 UTC, BYVoid commented
我大致看了基本可行，能說明一下這些字收集的來源嗎？

2020-04-03 03:25 UTC, edward-martyr commented
@edward-martyr 這些增補系從我個人在Rime使用的轉換碼表去重而來。其主要來源是Rime提供的[`nippon_variants`](https://github.com/rime-aca/customize)。另有我從 [ids](https://github.com/cjkvi/cjkvi-ids) 收集的一些字，竝不完全。

2020-04-12 15:36 UTC, BYVoid requested changes

2020-04-12 15:36 UTC, BYVoid commented on data/dictionary/JPVariants.txt
> +剾	𠛅
不建議加入Unicode BMP之外的擴張新字體。

2020-06-26 07:15 UTC, danny0838 commented
就我目前查到的資料，所謂擴張新字體是類似類推簡化字的字，並非官方明訂，但官方也未明確禁止使用。

我想，應該要考察日本實際使用情況，如果幾乎所有場合使用擴張新字體都是壓倒性的多數，可以直接加入。如果有為數不少的場合（例如正式場合用字等）不使用擴張新字體，或許擴張新字體應該獨立成另一個轉換表，並且把轉換方案分成「舊字體轉新字體」及「舊字體轉新字體（含擴張）」。

關於ByVoid提到應避免SMP用字的議題，我認為也需要考察，如果日本幾乎所有使用擴張新字體的場合都會使用那些SMP用字，那就應該加入；幾乎所有使用擴張新字體的場合都不使用，就不加入。如果有時會用有時不用，可以獨立成另一個表。

2026-05-07 04:09 UTC, frankslin commented
只保留 Unicode BMP 内的日文新字体映射，只剩下 6 组：

```
卮	巵
箋	䇳
粵	粤
蕭	䔥
鄰	隣
髡	髠
```

2026-06-13 11:42 UTC, frankslin commented
今后 JPShinjitaiCharacters.txt 内容，第一列以日本新字体文字为 key，原则上内容向「常用汉字表」等中的新旧字体对照靠拢，不再接受根据类推关系批量导入，也不再接受非「旧字体」的值。特殊情况可以词汇形式加入例外。

2026-06-13 11:43 UTC, closed without merging