增加一簡對多繁：你=>你妳
BYVoid/OpenCC pull request #472
Opened 2020-06-30 15:12 UTC by danny0838

2020-07-01 02:18 UTC, BYVoid commented
不建議列入，因爲實際上可能難以自動轉換，所需上下文太多。同時，在香港、臺灣，你、妳的混用也已經很多了。

2020-07-01 03:59 UTC, danny0838 commented
> 不建議列入，因爲實際上可能難以自動轉換，所需上下文太多。同時，在香港、臺灣，你、妳的混用也已經很多了。

不懂問題在哪？

主要是繁轉簡，按《通用規範漢字表》「妳」需要統一為「妳」，要區分「奶」可能比較困難，不過這用法主要只有古文會用，也許以後可以加幾個明確的詞，例如「吹妳」＝「吹奶」，不過和「陽谷」一樣還是會有一些誤判的機會就是，這可能是本質上難以避免的。

至於簡轉繁，實際上一般來說「你」並沒有轉換，只是增加一個「妳」的選項而已，和「它=>它牠」類似。

2020-07-08 03:23 UTC, BYVoid commented
我的理由是，「你」到「妳」的轉換幾乎無法自動完成。「它」「牠」也類似。

「奶」也並不是「妳」的簡化字。

2020-07-08 04:32 UTC, danny0838 commented
> 我的理由是，「你」到「妳」的轉換幾乎無法自動完成。「它」「牠」也類似。

不太可能自動轉換沒錯，但加了也不影響一般使用，而且讓使用一對多 API 時可以選擇。

再說「它=>它 牠」之前也加入了，這是一致性和完整性的問題。

> 「奶」也並不是「妳」的簡化字。

繁轉簡方案本來就是轉中國標準不是嗎？如果不是簡化字就不能列入，那「於」是否也不應轉成「于」，「恆」也不要轉成「恒」了？

2020-07-08 09:28 UTC, BYVoid commented on data/dictionary/TSCharacters.txt
> +妳	你 奶
建議刪去「妳->奶」轉換

2020-07-08 09:28 UTC, BYVoid requested changes
「你 妳」可以保持。

2020-07-08 09:32 UTC, danny0838 commented on data/dictionary/TSCharacters.txt
> +妳	你 奶
> 建議刪去「妳->奶」轉換

「妳=>你」和「妳=>奶」在《通用規範漢字表》裡都是「異體字」轉「規範字」的關係。這裡完全是按照《通用規範漢字表》實做。刪去一項的理由是什麼？

2020-07-08 09:41 UTC, BYVoid commented on data/dictionary/TSCharacters.txt
> +妳	你 奶
沒錯，理論上「妳」確實是「奶」的異體字，但是除了個別古文已經沒有這樣的用法。

事實上，我建議把此類的罕用異體字轉換從`TSCharacters.txt `和`STCharacters.txt `裏面分離出來，放入單獨的「古文異體字」（如`ArchaicVariants.txt`）。先有的其他古文異體字，如「蝎」等字也可以移除。

2020-07-08 09:47 UTC, danny0838 commented on data/dictionary/TSCharacters.txt
> +妳	你 奶
長遠來說可以這樣做。但是要考證所有「現代確定不常用，只有古文會用」的字做字典分離可能是個不小的工程。建議現階段先加，未來有需要再一次性做這樣的處理。

2020-07-08 11:40 UTC, BYVoid commented on data/dictionary/TSCharacters.txt
> +妳	你 奶
目前可以先加入TSCharacters.txt，同時也麻煩你建立另一個ArchaicVariants.txt，列入
```
妳	你 奶
```

這樣目的是避免以後遺忘

2020-07-08 12:29 UTC, danny0838 commented on data/dictionary/TSCharacters.txt
> +妳	你 奶
這個要討論的問題太多了……比如這裡是繁轉簡遇上這問題，但簡轉繁遇到這問題的機會可能有百倍以上，包括你前面提到的「蝎=>蠍 蝎」，還可以想到許多如「万」、「适」等等。那是否需要分成 TSArchaicVariants.txt 和 STArchaicVariants.txt？或是像地區詞那樣用 STArchaicVariants.txt 和 STArchaicVariantsRev.txt？

再來，檔案的內容需要包括「妳=>你」本身嗎？或是只需要「妳=>奶」即可？

要備忘有很多方法，比如另開一個 issue，或者記在自己的 TODO list。如果一定要寫在版本庫裡，在 scheme 下面另開一個檔案也比較不會混淆。

在這些相問題未解決以前，現在無論怎麼做，未來會被改掉的機會都是極大，加在這個 PR 恐怕太節外生枝了。

2020-07-21 02:48 UTC, BYVoid commented on data/dictionary/TSCharacters.txt
> +妳	你 奶
妳->奶 屬於古代異體字轉換。2013年通用規範漢字表裏（0782號）也沒有找到。

2020-07-21 04:09 UTC, danny0838 commented on data/dictionary/TSCharacters.txt
> +妳	你 奶
在 0332 號

2026-06-11 20:55 UTC, frankslin commented
t2s 「妳 -> 你」的转换会损失信息，且毫无必要。简中读者并不认为「妳」的出现是错字或无法理解。

2026-06-11 20:55 UTC, closed without merging