修正簡繁轉換及地區用字轉換：冢=>冢/塚
BYVoid/OpenCC pull request #515
Opened 2020-07-14 13:32 UTC by danny0838

之前的討論參見 #430 

「手塚」「鬼塚」等日本人名或許可以考慮加入 STPhrases.txt。

2020-07-21 02:40 UTC, BYVoid requested changes

2020-07-21 02:40 UTC, BYVoid commented on data/dictionary/JPVariants.txt
> +冢	塚
該轉換不屬於新字體。

2020-07-21 05:09 UTC, danny0838 commented on data/dictionary/JPVariants.txt
> +冢	塚
「塚」在《常用漢字表》中，「冢」不在《常用漢字表》、《人名用漢字表》、《表外漢字字體表》中，加上兩字是異體字關係，可以相信日本原則上會用「塚」取代「冢」，應比照其他「OpenCC 正體轉日本標準」的實例處理，如「內=>内」、「鬥=>闘」、「剎=>刹」。

2021-02-25 09:03 UTC, BYVoid commented on data/dictionary/JPVariants.txt
> +冢	塚
一般來說，日本傾向於不轉換不常見的異體字。我傾向於不變。

2021-02-25 13:53 UTC, danny0838 commented on data/dictionary/JPVariants.txt
> +冢	塚
> 一般來說，日本傾向於不轉換不常見的異體字。我傾向於不變。

這說法和 JPVariants.txt 表的慣例不符。目前 JPVariants.txt 表有包括 OpenCC 正體轉日本新字體，比如「內=>内」（參見 eeb533968fb7852b09424fd97d49aad12444684f）。而很顯然地，OpenCC 正體在日本都是「不常見的異體字」（日本人原則上會使用標準字，而不使用它們）。

2021-03-01 13:34 UTC, BYVoid commented on data/dictionary/JPVariants.txt
> +冢	塚
內 内 屬於字形不同的異體字，「冢 塚」還有古今關係。

日文有用「冢」的專有名詞。而沒有用「內」「剎」的專有名詞。

https://ja.wikipedia.org/wiki/%E6%B1%B2%E5%86%A2%E6%9B%B8
https://ja.wikipedia.org/wiki/%E5%86%A2%E7%94%B0%E5%A4%A7%E5%B3%AF

2021-03-04 11:08 UTC, danny0838 commented on data/dictionary/JPVariants.txt
> +冢	塚
你說的也對，但這樣就會造成比如台灣正體「塚」=>OpenCC正體「冢」=>日本新字體「冢」的問題，反而無法顧及大多數常用字。

比照其他OpenCC正體轉地區正體的情況，理論上應該是要為少數古字另外建詞庫處理才對。原轉換表可改成「冢=>塜冢」。

2026-06-12 00:42 UTC, closed without merging