修復與「涌」相關的錯誤轉換
BYVoid/OpenCC pull request #663
Opened 2022-02-24 01:36 UTC by groverlynn

修復與「涌」相關的錯誤轉換

2022-02-27 05:08 UTC, sgalal requested changes

2022-02-27 05:08 UTC, sgalal commented on data/dictionary/STPhrases.txt
> +蚝涌	蠔涌
蠔涌 don't need to be 蚝涌

2022-04-20 23:17 UTC, groverlynn commented on data/dictionary/STPhrases.txt
> +蚝涌	蠔涌
This is S to T. 蚝涌 should be converted to 蠔涌, which is the original name (HK).

2022-10-31 03:26 UTC, ayaka14732 approved these changes

2022-10-31 03:27 UTC, sgalal approved these changes

2022-10-31 03:27 UTC, merged