斗宿->斗宿
BYVoid/OpenCC pull request #737
Opened 2022-11-22 00:09 UTC by groverlynn

#590

2022-11-22 03:32 UTC, ayaka14732 requested changes

2022-11-22 03:32 UTC, ayaka14732 commented on data/dictionary/STPhrases.txt
> +气冲霄汉	氣沖霄漢
根據 OpenCC 標準 <https://github.com/BYVoid/OpenCC/blob/master/data/scheme/st_multi.txt>

```
冲	衝 沖 冲	與「撞擊」有關用「衝」，與「水流」有關用「沖」，「冲」見於古文。	要衝 衝突 俯衝 沖牛奶
```

2022-11-22 08:03 UTC, groverlynn commented on data/dictionary/STPhrases.txt
> +气冲霄汉	氣沖霄漢
參見氣沖沖

2022-11-22 13:46 UTC, ayaka14732 commented on data/dictionary/STPhrases.txt
> +气冲霄汉	氣沖霄漢
OpenCC 用字是一套規範用字，不是説社會上出現過的任何用法都要收錄。既然 OpenCC 已經這樣規定，那麼與 OpenCC 相左的用法就不會收錄進 OpenCC 詞表中。如果香港/台灣官方規定的用法不同，則要在 OpenCC 的香港/台灣轉換表中收錄，而非在簡繁轉換表中收錄。

2022-11-22 19:05 UTC, groverlynn commented on data/dictionary/STPhrases.txt
> +气冲霄汉	氣沖霄漢
所以你的意思是要收錄社會上從未出現過的、含有錯別字的「氣衝斗牛」？
何況那個辨析表也不是標準，只是指南。收錄的是常用簡繁非一一對應時的常見義項對應關係，而當中並無涉及「氣沖」。原本就是「氣沖」簡化成了「气冲」，從未有過「氣衝」，不應該生搬硬套一個逆向工程的指南，而自創「氣衝」。

2023-07-17 11:47 UTC, ayaka14732 approved these changes

2023-07-17 11:47 UTC, merged