STPhrases「谷阳」等
BYVoid/OpenCC pull request #881
Opened 2024-07-27 09:01 UTC by SteveLz

2024-07-27 13:16 UTC, BYVoid commented
Please run `python3 data/scripts/sort_all.py data/dictionary`

2024-07-29 15:05 UTC, BYVoid requested changes

2024-07-29 15:05 UTC, BYVoid commented on data/dictionary/STPhrases.txt
> +标里	標里
建議改成 [標里鎮](https://zh.wikipedia.org/zh-hant/%E6%A0%87%E9%87%8C%E9%95%87)

2024-07-29 15:05 UTC, BYVoid commented on data/dictionary/STPhrases.txt
> +生发	生髮 生發
生發 是什麼

2024-07-29 15:05 UTC, BYVoid commented on data/dictionary/STPhrases.txt
> +鼠标里面	鼠標裡面
OpenCC默認「裏」

2024-07-29 17:15 UTC, SteveLz commented on data/dictionary/STPhrases.txt
> +生发	生髮 生發
似有用例

> 「倭寇生發，沿海搶劫，各州縣地方，須用心巡警，以防衝犯。」

也有部分以此命名的實體，若無必要也可刪去，衹是不知檢查失在何處

2024-11-14 21:09 UTC, BYVoid approved these changes

2024-11-14 21:10 UTC, merged